/*
 *  Copyright 2020-2022 NXP
 *  All rights reserved.
 *
 *  SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _WIFI_CONFIG_H_
#define _WIFI_CONFIG_H_

#define CONFIG_WIFI_MAX_PRIO (configMAX_PRIORITIES - 1)
#define PRINTF_FLOAT_ENABLE 1

#define CONFIG_MAX_AP_ENTRIES 30
#define CONFIG_NCP_5GHz_SUPPORT 1
#define CONFIG_NCP_11AC
/* OWE mode */
#define CONFIG_NCP_OWE
/* WLAN SCAN OPT */
#define CONFIG_NCP_SCAN_WITH_RSSIFILTER
#define CONFIG_NCP_WIFI_DTIM_PERIOD
#define CONFIG_NCP_WIFI_CAPA
#define CONFIG_NCP_11R  1


#define CONFIG_NCP_IPV6               1
#define CONFIG_MAX_IPV6_ADDRESSES 3

/* Logs */
#define CONFIG_ENABLE_ERROR_LOGS   1
#define CONFIG_ENABLE_WARNING_LOGS 1

#define CONFIG_NCP_SUPP

#define CONFIG_NCP_BRIDGE
/*MCU BRIDGE Bridge debug options*/
#undef CONFIG_NCP_HOST_DEBUG
#undef CONFIG_NCP_HOST_IO_DUMP
#undef CONFIG_CRC32_HW_ACCELERATE
#define CONFIG_NCP_RF_TEST_MODE
#define CONFIG_NCP_MEM_MONITOR_DEBUG

/*https client and websocket*/
#define CONFIG_ENABLE_HTTPC_SECURE
#define CONFIG_ENABLE_TLS
#define APPCONFIG_WEB_SOCKET_SUPPORT
#undef CONFIG_HTTPC_DEBUG

//#define CONFIG_NCP_UART
//#define CONFIG_SPI_BRIDGE
#define CONFIG_USB_BRIDGE
//#define CONFIG_NCP_SDIO
//#define CONFIG_SDIO_IO_DEBUG

/*
 * Heap debug options
 */
#undef CONFIG_NCP_HEAP_DEBUG
#undef CONFIG_NCP_HEAP_STAT


#ifdef CONFIG_NCP_SUPP
#define CONFIG_NCP_WPA_SUPP 1
#ifdef CONFIG_NCP_WPA_SUPP
//#define CONFIG_WPA_SUPP_P2P 1
#undef CONFIG_NCP_WPA_SUPP_DPP
#define CONFIG_NCP_WPA_SUPP_CRYPTO_ENTERPRISE 1
#define CONFIG_NCP_WPA_SUPP_CRYPTO_AP_ENTERPRISE 1

#if defined(CONFIG_NCP_WPA_SUPP_CRYPTO_ENTERPRISE) || defined(CONFIG_NCP_WPA_SUPP_CRYPTO_AP_ENTERPRISE)
#define CONFIG_NCP_EAP_TLS
#define CONFIG_NCP_EAP_PEAP
#define CONFIG_NCP_EAP_TTLS
#define CONFIG_NCP_EAP_FAST
#define CONFIG_NCP_EAP_SIM
#define CONFIG_NCP_EAP_AKA
#define CONFIG_NCP_EAP_AKA_PRIME

#if defined(CONFIG_NCP_EAP_PEAP) || defined(CONFIG_NCP_EAP_TTLS) || defined(CONFIG_NCP_EAP_FAST)
#define CONFIG_NCP_EAP_MSCHAPV2
#define CONFIG_NCP_EAP_GTC
#endif
#endif

#else

#endif

#if defined(CONFIG_WIFI_USB_FILE_ACCESS) && defined(CONFIG_USB_BRIDGE)  
    #error " CONFIG_USB_BRIDGE and CONFIG_WIFI_USB_FILE_ACCESS are exclusive for ncp and ncp_supp"
#endif
#else

#define CONFIG_NCP_WPS2
#define CONFIG_NCP_WPA2_ENTP
#undef CONFIG_NCP_WPA_SUPP
#endif /*CONFIG_NCP_SUPP*/

#endif /* _WIFI_CONFIG_H_ */
